project:
  type: website
  output-dir: docs

website:
  title: "Iceland 2025"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - route.qmd
      - waterfalls.qmd
      - animals.qmd
      - plants.qmd
      - closeread_example.qmd
    right:
      - icon: github
        href: https://github.com/NoahBolohan/Iceland-2025
        aria-label: GitHub

format:
  closeread-html:
    theme: cosmo
    css: styles.css
    embed-resources: true
    cr-style:
      section-background-color: "#4d4d4d"
      narrative-text-color-sidebar: "#bfbfbf"