project:
  type: website
  output-dir: docs

website:
  title: "Iceland 2025"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: black
    foreground: darkgrey
    left:
      - href: index.qmd
        text: Home
      - route.qmd
      - waterfalls.qmd
      - animals.qmd
      - plants.qmd
    right:
      - icon: github
        href: https://github.com/NoahBolohan/Iceland-2025
        aria-label: GitHub

format:
  closeread-html:
    embed-resources: true
    cr-style:
      section-background-color: "#4d4d4d"
      narrative-text-color-sidebar: "#bfbfbf"