---
title: Waterfalls
page-layout: full
listing:
  - id: listing-oxararfoss
    template: gallery.ejs
    contents:
        - /static/waterfalls/oxararfoss/*.jpg
    sort-ui: false
    filter-ui: false
    categories: false
  - id: listing-gullfoss
    template: gallery.ejs
    contents:
        - /static/waterfalls/gullfoss/*.jpg
    sort-ui: false
    filter-ui: false
    categories: false
  - id: listing-barnafoss
    template: gallery.ejs
    contents:
        - /static/waterfalls/barnafoss/*.jpg
    sort-ui: false
    filter-ui: false
    categories: false
---

Throughout Iceland, there are many glaciers; the 3 largest are Vatnajökull, Langjökull, and Hofsjökull, but there are hundreds of other smaller glaciers all over the country, covering about 10% of the land (around 10,400 square kilometers). As a result, there are also waterfalls all over the place! Here are a few that we visited during our trip:

:::: {.columns}

::: {.column width="75%"}

# Öxarárfoss - *Öxará falls* or *Axe river falls*

## June 18th, 2025

The first waterfall we visited in Iceland was **Öxarárfoss**, inheriting it's name from the **Öxará river** from which it flows.

This waterfall is located in the **Þingvellir National Park**, which was the site of the **Alþing**, the annual parliament of Iceland from the year 930 until the last session held at Þingvellir in 1798. Since 1881, the parliament has been located within Alþingishúsið in Reykjavík.

<!-- ::: {#listing-oxararfoss}
::: -->

:::

::: {.column width="5%"}

:::

::: {.column width="20%"}

{{< video https://www.youtube.com/embed/a5-Qaz0-7lw width="337.5" height="600" >}}

:::

::::

:::: {.columns}

::: {.column width="55%"}

# Gullfoss - *Golden falls*

## June 18th, 2025

The second waterfall we visited was **Gullfoss** (*Golden falls*), one of the most popular tourist attractions in Iceland. It is sourced from the **Hvítá river** which begins at **Hvítárvatn glacier lake** on **Langjökull glacier**.

Gullfoss is huge! The average amount of water running down the waterfall is 141 cubic meters per second but the highest flood measured was 2,000 cubic meters.

During the 20th century, there was interest in harnessing the power of Gullfoss to generate electricity. **Sigríður Tómasdóttir** (1874-1957), daughter of the co-owner of the land at the time, is popularly credited with saving the waterfall from exploitation, often walking 120km (one-way) to Reykjavik to further case and even threatening to throw herself in the waterfalls. Eventually, Gullfoss became the property of the people of Iceland and was made a permanent conservation site in 1979.

<!-- ::: {#listing-gullfoss}
::: -->

:::

::: {.column width="5%"}

:::

::: {.column width="40%"}

{{< video https://www.youtube.com/embed/euG1sbnehMY width="600" height="337.5" >}}

{{< video https://www.youtube.com/embed/RNCUnOuAXfA width="600" height="337.5" >}}

:::

::::

:::: {.columns}

::: {.column width="75%"}

# Barnafoss - *Children's falls*

## June 20th, 2025

Once we left Reykjavik, we stopped by the waterfall pair of **Barnafoss** and **Hraunfossar**. Both of these falls lie on the **Hvítá**, which is the same source as **Gullfoss**. The more upstream of the two is **Barnafoss**.

Many Icelandic folktales are associated with **Barnafoss**, the most famous bring about two boys from the the nearby farm of **Hraunsás**. One day, their parents went to church and the boys were supposed to stay home. However, they grew bored and followed their parents, making a shortcut which crossed a natural stone-bridge that was above the waterfall. On their way, they felt dizzy and fells into the water and drowned. When their mother found out what happened, she put a spell on the bridge, saying that nobody would ever cross it without drowning himself. A little while later, the bridge was demolished in an earthquake.

<!-- ::: {#listing-barnafoss}
::: -->

:::

::: {.column width="5%"}

:::

::: {.column width="20%"}

{{< video https://www.youtube.com/embed/F3vM0u25pOU width="337.5" height="600" >}}

{{< video https://www.youtube.com/embed/HFzTtjHTeQ0 width="337.5" height="600" >}}

{{< video https://www.youtube.com/embed/Diat8Yijojw width="337.5" height="600" >}}

:::

::::